### ISSUE TITLE
Error al Firmar: Unable to cast object

### ISSUE THREAD

**Issue by C26000** [miguelhuertas/eFacturacionColombia_V2.Firma#6]
Hola,

Estoy tratando de adaptar la librería a mi proyecto y luce muy prometedora, ¡gracias! Sin embargo, al realizar la primera prueba me sacó esta excepción 
`'Unable to cast object of type System.Security.Cryptography.RSACng' to type System.Security.Cryptography.RSACryptoServiceProvider'.'` Uso Visual Studio 2019 en Windows 10.

Esta es la ruta de la excepción

```
   at FirmaXadesNet.Crypto.Signer.SetSigningKey(X509Certificate2 certificate)
   at FirmaXadesNet.Crypto.Signer..ctor(X509Certificate2 certificate)
   at eFacturacionColombia_V2.Firma.FirmaElectronica.FirmarDocumento(Byte[] bytesXml, DateTime fecha, SignatureXPathExpression xpathExpression)
   at eFacturacionColombia_V2.Firma.FirmaElectronica.FirmarFactura(Byte[] bytesXml, DateTime fecha)
   at eFacturacionColombia_V2.Firma.FirmaElectronica.FirmarFactura(FileInfo archivo, DateTime fecha)
   at SimpleOps.Legal.DocumentoElectrónico`2.Firmar() in D:\Nubes\Dropbox\Desarrollos\SimpleOps\Código\SimpleOps\SimpleOps\Legal\DocumentoElectrónico.cs:line 1019
   at SimpleOps.Legal.DocumentoElectrónico`2.CrearXml(String& mensaje) in D:\Nubes\Dropbox\Desarrollos\SimpleOps\Código\SimpleOps\SimpleOps\Legal\DocumentoElectrónico.cs:line 983
   at SimpleOps.Pruebas.FacturaEjemploXml() in D:\Nubes\Dropbox\Desarrollos\SimpleOps\Código\SimpleOps\SimpleOps\Estáticas\Pruebas.cs:line 712
   at SimpleOps.Pruebas.DocumentosElectrónicos() in D:\Nubes\Dropbox\Desarrollos\SimpleOps\Código\SimpleOps\SimpleOps\Estáticas\Pruebas.cs:line 383
   at SimpleOps.Interfaz.Principal..ctor() in D:\Nubes\Dropbox\Desarrollos\SimpleOps\Código\SimpleOps\SimpleOps\Interfaz\Ventanas\Principal.xaml.cs:line 71

```

Este es el código que estoy usando para la firma. 

```
        public bool Firmar() {

            if (!File.Exists(RutaCertificado)) throw new Exception($"No existe el certificado {RutaCertificado}.");
            var rutaXmlSinFirma = ObtenerRutaXml(firmado: false);
            var firma = new FirmaElectronica { RolFirmante = RolFirmante.EMISOR,  RutaCertificado = RutaCertificado, ClaveCertificado = ClaveCertificado };
            var archivoXml = new FileInfo(rutaXmlSinFirma);
            var facturaFirmada = firma.FirmarFactura(archivoXml, AhoraUtcAjustado);
            File.WriteAllBytes(ObtenerRutaXml(firmado: true), facturaFirmada);
            IntentarBorrar(rutaXmlSinFirma);
            return true;

        } 

```

Algo que noté diferente es que mi certificado es un .pfx en vez de .p12. ¿Esto tendrá algo que ver? También agregué la bibliotoeca como un dll a mi proyecto, no como código directamente, ¿O tal vez será esto?

Gracias por cualquier ayuda que me puedas brindar.

Saludos

**Comment by miguelhuertas** [comment]
Gracias @C26000. Tomaré en cuenta tu reporte para futuras actualizaciones.

**Comment by DavidRill** [comment]
Hola Miguel, Tengo un problema de privacidad que me está afectando y necesito eliminar todo rastro de mi nombre de usuario anterior. Sería posible que editaras tu respuesta anterior y le quitaras mi nombre de usuario anterior? Me ayudarías mucho para mi tranquilidad. Gracias y Saludos!

**Comment by DavidRill** [comment]
Hola Miguel, Te agradezco mucho la edición, pero justo me acabo de dar cuenta que mi nombre de usuario anterior sigue estando en el edited... Sería mucha molestia si eliminaras el mensaje que me diste de respuesta para que no aparezca más? 
Muchas gracias de antemano!
David
